# Generated by Django 3.1.2 on 2020-10-17 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20201014_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fio',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mapsDocAppointment', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mapsUserAppointment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
