# Generated by Django 3.1.2 on 2020-10-17 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20201017_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='docId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mapsDocAppointment', to='myApp.specialty'),
        ),
    ]
